name: redactly
description: Local text redaction with placeholder mapping.
version: 0.2.1+8
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.2
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  window_manager: ^0.4.0
  material_symbols_icons: ^4.2719.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

icons_launcher:
  image_path: assets/images/app_icon.png
  platforms:
    macos:   { enable: true }
    windows: { enable: true }
    linux:   { enable: true }
